---
- name: Setup iptable rules on wesley-headnode
  hosts: wesley-headnode
  become: yes
  tasks:
    - name: Ensure iptables-persistent is installed
      apt:
          name: iptables-persistent
          state: present
          update_cache: yes

    - name: Set NAT POSTROUTING rule
      command: iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE
    
    - name: Allow forwarded traffic from internal to external network
      command: iptables -A FORWARD -i ens19 -o ens18 -j ACCEPT

    - name: Allow forwarded traffic from external to internal network
      command: iptables -A FORWARD -i ens18 -o ens19 -m state --state ESTABLISHED,RELATED -j ACCEPT

    - name: Save iptables rules
      shell: iptables-save > /etc/iptables/rules.v4

    - name: Ensure iptables-persistent service is enabled and started
      systemd:
        name: netfilter-persistent
        enabled: yes
        state: started